### ISSUE TITLE
Help with an error

### ISSUE THREAD

**Issue by pidugusundeep** [davidguttman/s3-rsync#3]
```
/usr/local/lib/node_modules/s3-rsync/node_modules/knox/lib/client.js:363
    var contentType = mime.lookup(src);
                           ^

TypeError: mime.lookup is not a function
    at /usr/local/lib/node_modules/s3-rsync/node_modules/knox/lib/client.js:363:28
    at FSReqCallback.oncomplete (fs.js:160:5)

```

**Comment by pidugusundeep** [comment]
Solved this.
